default_context:
  project_name: 'auth service'
  project_slug: 'auth-service'
  domain_main: 'auth-service.esesen.com'
  domain_staging: 'stag.auth-service.esesen.com'
  docker_swarm_stack_name_main: 'auth-service-esesen-com'
  docker_swarm_stack_name_staging: 'stag-auth-service-esesen-com'
  secret_key: 's0mesecretn4me'
  first_superuser: 'admin@auth-service.esesen.com'
  first_superuser_password: '4dminp4ssw0rd'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.auth-service.esesen.com", "https://stag.auth-service.esesen.com", "https://auth-service.esesen.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@auth-service.esesen.com'
  postgres_password: 'p0stgresp4ssw0rd'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: '4dminp4ssw0rd'
  traefik_constraint_tag: 'auth-service.esesen.com'
  traefik_constraint_tag_staging: 'stag.auth-service.esesen.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:4dminp4ssw0rd'
  sentry_dsn: ''
  docker_image_prefix: 'auth-service'
  docker_image_backend: 'auth-servicebackend'
  docker_image_celeryworker: 'auth-serviceceleryworker'
  docker_image_frontend: 'auth-servicefrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
